export const SET_VIEW = "SET_VIEW";

// #region Market Index
export const SET_INDEX_VALUE_TIME_SCOPE = "SET_INDEX_VALUE_TIME_SCOPE";

export const SET_SELECTED_INDEX_ID = "SET_SELECTED_INDEX_ID";

export const TOGGLE_MARKET_INDEX_SELECTION = "TOGGLE_MARKET_INDEX_SELECTION";
export const TOGGLE_ALL_MARKET_INDEX_SELECTION = "TOGGLE_ALL_MARKET_INDEX_SELECTION";
export const DELETE_MARKET_INDEX_COMPLETED = "DELETE_MARKET_INDEX_COMPLETED";

export const OPEN_EDIT_MARKET_INDEX_DETAILS_MODAL = "OPEN_EDIT_MARKET_INDEX_DETAILS_MODAL";
export const CLOSE_EDIT_MARKET_INDEX_DETAILS_MODAL = "CLOSE_EDIT_MARKET_INDEX_DETAILS_MODAL";

export const OPEN_NEW_MARKET_INDEX_DETAILS_MODAL = "OPEN_NEW_MARKET_INDEX_DETAILS_MODAL";
export const CLOSE_NEW_MARKET_INDEX_DETAILS_MODAL = "CLOSE_NEW_MARKET_INDEX_DETAILS_MODAL";

export const OPEN_DELETE_MARKET_INDEX_MODAL = "OPEN_DELETE_MARKET_INDEX_MODAL";
export const CLOSE_DELETE_MARKET_INDEX_MODAL = "CLOSE_DELETE_MARKET_INDEX_MODAL";

export const SET_MARKET_INDEX_LIST_FILTER_STRING = "SET_MARKET_INDEX_LIST_FILTER_STRING";

export const LOAD_MARKET_INDEXES_STARTED = "LOAD_MARKET_INDEXES_STARTED";
export const LOAD_MARKET_INDEXES_COMPLETED = "LOAD_MARKET_INDEXES_COMPLETED";

export const DELETE_SINGLE_MARKET_INDEX_STARTED = "DELETE_SINGLE_MARKET_INDEX_STARTED";
export const DELETE_SINGLE_MARKET_INDEX_COMPLETED = "DELETE_SINGLE_MARKET_INDEX_COMPLETED";
export const DELETE_SINGLE_MARKET_INDEX_FAILED = "DELETE_SINGLE_MARKET_INDEX_FAILED";

export const TOGGLE_SIEVO_INDEX_STATUS_STARTED = "TOGGLE_SIEVO_INDEX_STATUS_STARTED";
export const TOGGLE_SIEVO_INDEX_STATUS_FAILED = "TOGGLE_SIEVO_INDEX_STATUS_FAILED";
export const TOGGLE_SIEVO_INDEXES_STATUS_COMPLETED = "TOGGLE_SIEVO_INDEXES_STATUS_COMPLETED";
// #endregion

// #region Market Index Value
export const LOAD_MARKET_INDEX_VALUES_STARTED = "LOAD_MARKET_INDEX_VALUES_STARTED";
export const LOAD_MARKET_INDEX_VALUES_COMPLETED = "LOAD_MARKET_INDEX_VALUES_COMPLETED";

export const UPDATE_MARKET_INDEX_VALUE_COMPLETED = "UPDATE_MARKET_INDEX_VALUE_COMPLETED";
export const UPDATE_MARKET_INDEX_VALUE_VALIDATION_COMPLETED = "UPDATE_MARKET_INDEX_VALUE_VALIDATION_COMPLETED";
// #endregion

// #region Cost Structure
export const LOAD_COST_STRUCTURES_STARTED = "LOAD_COST_STRUCTURES_STARTED";
export const LOAD_COST_STRUCTURES_COMPLETED = "LOAD_COST_STRUCTURES_COMPLETED";
export const LOAD_COST_STRUCTURES_FAILED = "LOAD_COST_STRUCTURES_FAILED";

export const OPEN_NEW_COST_STRUCTURE_MODAL = "OPEN_NEW_COST_STRUCTURE_MODAL";
export const CLOSE_NEW_COST_STRUCTURE_MODAL = "CLOSE_NEW_COST_STRUCTURE_MODAL";
export const SET_COST_STRUCTURE_EDIT_FORM_FIELD_DATA = "SET_COST_STRUCTURE_EDIT_FORM_FIELD_OPTIONS";

export const CREATE_COST_STRUCTURE_COMPLETED = "CREATE_COST_STRUCTURE_COMPLETED";
export const CREATE_COST_STRUCTURE_FAILED = "CREATE_COST_STRUCTURE_FAILED";
// #endregion
